# Generated by Django 2.1 on 2018-08-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='business',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='company',
            name='url',
            field=models.CharField(max_length=150),
        ),
    ]
