# Generated by Django 2.1 on 2018-08-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0002_auto_20180818_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='companyinfo',
            unique_together={('ticker_symbol', 'param_name')},
        ),
    ]
